ALTER TABLE project ADD COLUMN staff_budget NUMERIC(10,2) NOT NULL DEFAULT 100000;
ALTER TABLE project ADD COLUMN travel_budget NUMERIC(10,2) NOT NULL DEFAULT 100000;
ALTER TABLE project ADD COLUMN equipment_budget NUMERIC(10,2) NOT NULL DEFAULT 100000;
ALTER TABLE project ADD COLUMN subcontracting_budget NUMERIC(10,2) NOT NULL DEFAULT 100000;
ALTER TABLE project ADD COLUMN indirect_budget NUMERIC(10,2) NOT NULL DEFAULT 60000;

ALTER TABLE project ALTER COLUMN staff_budget DROP DEFAULT;
ALTER TABLE project ALTER COLUMN travel_budget DROP DEFAULT;
ALTER TABLE project ALTER COLUMN equipment_budget DROP DEFAULT;
ALTER TABLE project ALTER COLUMN subcontracting_budget DROP DEFAULT;
ALTER TABLE project ALTER COLUMN indirect_budget DROP DEFAULT;