name: Build and deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -Dspring.config.location=src/main/resources/ci-application.properties --file pom.xml

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: target/*.jar
          target: ~/root/projectmanager

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          PASSWORD: ${{ secrets.USER_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: PASSWORD
          script: |
            cd ~/root/projectmanager
            rm app.jar
            mv target/*.jar app.jar
            rm -rf app/target
            echo $PASSWORD | sudo -S systemctl restart projectmanager
